CREATE WAREHOUSE IF NOT EXISTS LIGHTHOUSE_DEV_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS LIGHTHOUSE_DEV;

USE WAREHOUSE LIGHTHOUSE_DEV_WH;
USE DATABASE LIGHTHOUSE_DEV;

CREATE SCHEMA IF NOT EXISTS RAW;

CREATE OR REPLACE FILE FORMAT RAW.LIGHTHOUSE_SCENARIO_CSV
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null');

CREATE TABLE IF NOT EXISTS RAW.ORDERS (
  scenario_id VARCHAR,
  record_source VARCHAR,
  ingest_batch_id VARCHAR,
  order_id VARCHAR,
  customer_id VARCHAR,
  vin VARCHAR,
  market VARCHAR,
  order_status VARCHAR,
  order_amount NUMBER(18, 2),
  source_updated_at TIMESTAMP_NTZ,
  loaded_at TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.VEHICLE (
  scenario_id VARCHAR,
  record_source VARCHAR,
  ingest_batch_id VARCHAR,
  vin VARCHAR,
  vehicle_id VARCHAR,
  make VARCHAR,
  model VARCHAR,
  market VARCHAR,
  source_updated_at TIMESTAMP_NTZ,
  loaded_at TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS RAW.SCENARIO_LOAD_AUDIT (
  scenario_id VARCHAR,
  loaded_at TIMESTAMP_NTZ,
  loaded_by VARCHAR,
  orders_rows NUMBER,
  vehicle_rows NUMBER
);
